<style>
pre {
  overflow-x: scroll !important;
}
pre code {
  white-space: pre !important;
  word-break: keep-all !important;
  word-wrap: initial !important;
}
</style>
```{r, echo=FALSE}
options(width = 200)
```


```{r, message=FALSE}
library(rvest)
library(tidyverse)
library(reshape2)
```
```{r}

all_data <- ""
for (month in 1:6) {
html_string <- paste("https://bkm.com.tr/secilen-aya-ait-sektorel-gelisim/?filter_year=2019&filter_month=",
                     month,sep='')
bkm_sektor <- read_html(html_string)
bkm_table <- html_nodes(bkm_sektor, "table")
my_table <- html_table(bkm_table[4],fill = TRUE)  %>%  as.data.frame() %>% slice(3:max(nrow(.)-1)) 
my_table <- my_table %>% mutate(MONHT=month)
all_data <- rbind(all_data,my_table)
}



colnames(all_data) <- c("work_group", "cc_sales_volume", 
                        "bc_sales_volume", "cc_trans_cost", "bc_trans_cost","MONTH")

all_data$cc_sales_volume <- as.numeric(str_replace_all(all_data$cc_sales_volume, pattern=fixed("."), ""))
all_data$bc_sales_volume <- as.numeric(str_replace_all(all_data$bc_sales_volume, pattern=fixed("."), ""))

all_data$cc_trans_cost<-str_replace_all(all_data$cc_trans_cost, pattern=fixed("."), "")
all_data$cc_trans_cost<-as.numeric(str_replace_all(all_data$cc_trans_cost, pattern=fixed(","), "."))

all_data$bc_trans_cost<-str_replace_all(all_data$bc_trans_cost, pattern=fixed("."), "")
all_data$bc_trans_cost<-as.numeric(str_replace_all(all_data$bc_trans_cost, pattern=fixed(","), "."))

head(all_data)
                                
```

### Analysis 1 - Calculating Unit Price of Transactions and Monthly Comparision (BIREYSEL EMEKLILIK)

```{r}
analysis_1_CC <- all_data %>% filter(work_group == "BIREYSEL EMEKLILIK") %>% mutate(UNITPRICE=cc_trans_cost*1000000/cc_sales_volume, type='Credit Card')

analysis_1_BC <- all_data %>% filter(work_group == "BIREYSEL EMEKLILIK") %>% mutate(UNITPRICE=bc_trans_cost*1000000/bc_sales_volume, type='Bank Card')


analysis_1 <- rbind(analysis_1_CC,analysis_1_BC)

print(analysis_1)

```
```{r}

ggplot(analysis_1, aes(x=MONTH, y=UNITPRICE, fill=type))+geom_bar(stat="identity",position="dodge")+labs(x="Month",y="Unit Price of Transaction",title="Unit Price of Transactions and Monthly Comparision(BIREYSEL EMEKLILIK)")
```





